#!/bin/bash

# # CheXpert

# # CXR-FM-LP
# python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'chexpert' --model_shortname 'CXR-FM-LP' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_chexpert/CheXpert_All_Selected_Models/CheXpert_CXR-FM_linear-probing_multirun-seed45'
# # CXR-Model-LP
# python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'chexpert' --model_shortname 'CXR-Model-LP' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_chexpert/CheXpert_All_Selected_Models/CheXpert_CXR-model_linear-probing_multirun-seed42'
# # CXR-Model-FFT
# python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'chexpert' --model_shortname 'CXR-Model-FFT' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_chexpert/CheXpert_All_Selected_Models/CheXpert_CXR-model_full-finetuning_multirun-seed44'

# # KD-MSE
# python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'chexpert' --model_shortname 'CXR-FMKD-LP (MSE)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_chexpert/CheXpert_All_Selected_Models/KD-MSE/CheXpert_CXR-FMKD_linear-probing_multirun-seed43' --kd_type_subdir_name 'KD-MSE'
# python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'chexpert' --model_shortname 'CXR-FMKD-FFT (MSE)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_chexpert/CheXpert_All_Selected_Models/KD-MSE/CheXpert_CXR-FMKD_full-finetuning_multirun-seed43' --kd_type_subdir_name 'KD-MSE'
# python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'chexpert' --model_shortname 'CXR-FMKD-Direct-LP (MSE)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_chexpert/CheXpert_All_Selected_Models/KD-MSE/CheXpert_CXR-FMKD-1664to14_linear-probing_multirun-seed42' --kd_type_subdir_name 'KD-MSE'
# python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'chexpert' --model_shortname 'CXR-FMKD-Direct-FFT (MSE)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_chexpert/CheXpert_All_Selected_Models/KD-MSE/CheXpert_CXR-FMKD-1664to14_full-finetuning_multirun-seed42' --kd_type_subdir_name 'KD-MSE'

# # KD-CS
# python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'chexpert' --model_shortname 'CXR-FMKD-LP (CS)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_chexpert/CheXpert_All_Selected_Models/KD-CosineSim/CheXpert_CXR-FMKD_linear-probing_multirun-seed44' --kd_type_subdir_name 'KD-CosineSim'
# python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'chexpert' --model_shortname 'CXR-FMKD-FFT (CS)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_chexpert/CheXpert_All_Selected_Models/KD-CosineSim/CheXpert_CXR-FMKD_full-finetuning_multirun-seed43' --kd_type_subdir_name 'KD-CosineSim'
# python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'chexpert' --model_shortname 'CXR-FMKD-Direct-LP (CS)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_chexpert/CheXpert_All_Selected_Models/KD-CosineSim/CheXpert_CXR-FMKD-1664to14_linear-probing_multirun-seed43' --kd_type_subdir_name 'KD-CosineSim'
# python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'chexpert' --model_shortname 'CXR-FMKD-Direct-FFT (CS)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_chexpert/CheXpert_All_Selected_Models/KD-CosineSim/CheXpert_CXR-FMKD-1664to14_full-finetuning_multirun-seed45' --kd_type_subdir_name 'KD-CosineSim'

# # KD-MSE-CS | 0.6-0.4
# python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'chexpert' --model_shortname 'CXR-FMKD-LP (MSE-CS | 0.6-0.4)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_chexpert/CheXpert_All_Selected_Models/KD-MSEandCosineSimWeighted-alpha0p60/CheXpert_CXR-FMKD_linear-probing_multirun-seed43' --kd_type_subdir_name 'KD-MSEandCosineSimWeighted-alpha0p60'
# python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'chexpert' --model_shortname 'CXR-FMKD-FFT (MSE-CS | 0.6-0.4)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_chexpert/CheXpert_All_Selected_Models/KD-MSEandCosineSimWeighted-alpha0p60/CheXpert_CXR-FMKD_full-finetuning_multirun-seed41' --kd_type_subdir_name 'KD-MSEandCosineSimWeighted-alpha0p60'
# python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'chexpert' --model_shortname 'CXR-FMKD-Direct-LP (MSE-CS | 0.6-0.4)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_chexpert/CheXpert_All_Selected_Models/KD-MSEandCosineSimWeighted-alpha0p60/CheXpert_CXR-FMKD-1664to14_linear-probing_multirun-seed43' --kd_type_subdir_name 'KD-MSEandCosineSimWeighted-alpha0p60'
# python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'chexpert' --model_shortname 'CXR-FMKD-Direct-FFT (MSE-CS | 0.6-0.4)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_chexpert/CheXpert_All_Selected_Models/KD-MSEandCosineSimWeighted-alpha0p60/CheXpert_CXR-FMKD-1664to14_full-finetuning_multirun-seed41' --kd_type_subdir_name 'KD-MSEandCosineSimWeighted-alpha0p60'


# MIMIC

# CXR-FM-LP
python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'mimic' --model_shortname 'CXR-FM-LP' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_mimic/MIMIC_All_Selected_Models/MIMIC_CXR-FM_linear-probing_multirun-seed43'
# CXR-Model-LP
python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'mimic' --model_shortname 'CXR-Model-LP' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_mimic/MIMIC_All_Selected_Models/MIMIC_CXR-model_linear-probing_multirun-seed41'
# CXR-Model-FFT
python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'mimic' --model_shortname 'CXR-Model-FFT' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_mimic/MIMIC_All_Selected_Models/MIMIC_CXR-model_full-finetuning_multirun-seed45'

# KD-MSE
python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'mimic' --model_shortname 'CXR-FMKD-LP (MSE)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_mimic/MIMIC_All_Selected_Models/KD-MSE/MIMIC_CXR-FMKD_linear-probing_multirun-seed41' --kd_type_subdir_name 'KD-MSE'
python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'mimic' --model_shortname 'CXR-FMKD-FFT (MSE)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_mimic/MIMIC_All_Selected_Models/KD-MSE/MIMIC_CXR-FMKD_full-finetuning_multirun-seed42' --kd_type_subdir_name 'KD-MSE'
python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'mimic' --model_shortname 'CXR-FMKD-Direct-LP (MSE)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_mimic/MIMIC_All_Selected_Models/KD-MSE/MIMIC_CXR-FMKD-1664to14_linear-probing_multirun-seed41' --kd_type_subdir_name 'KD-MSE'
python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'mimic' --model_shortname 'CXR-FMKD-Direct-FFT (MSE)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_mimic/MIMIC_All_Selected_Models/KD-MSE/MIMIC_CXR-FMKD-1664to14_full-finetuning_multirun-seed42' --kd_type_subdir_name 'KD-MSE'

# KD-CS
python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'mimic' --model_shortname 'CXR-FMKD-LP (CS)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_mimic/MIMIC_All_Selected_Models/KD-CosineSim/MIMIC_CXR-FMKD_linear-probing_multirun-seed42' --kd_type_subdir_name 'KD-CosineSim'
python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'mimic' --model_shortname 'CXR-FMKD-FFT (CS)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_mimic/MIMIC_All_Selected_Models/KD-CosineSim/MIMIC_CXR-FMKD_full-finetuning_multirun-seed45' --kd_type_subdir_name 'KD-CosineSim'
python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'mimic' --model_shortname 'CXR-FMKD-Direct-LP (CS)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_mimic/MIMIC_All_Selected_Models/KD-CosineSim/MIMIC_CXR-FMKD-1664to14_linear-probing_multirun-seed41' --kd_type_subdir_name 'KD-CosineSim'
python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'mimic' --model_shortname 'CXR-FMKD-Direct-FFT (CS)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_mimic/MIMIC_All_Selected_Models/KD-CosineSim/MIMIC_CXR-FMKD-1664to14_full-finetuning_multirun-seed45' --kd_type_subdir_name 'KD-CosineSim'

# KD-MSE-CS | 0.6-0.4
python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'mimic' --model_shortname 'CXR-FMKD-LP (MSE-CS | 0.9-0.1)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_mimic/MIMIC_All_Selected_Models/KD-MSEandCosineSimWeighted-alpha0p90/MIMIC_CXR-FMKD_linear-probing_multirun-seed43' --kd_type_subdir_name 'KD-MSEandCosineSimWeighted-alpha0p90'
python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'mimic' --model_shortname 'CXR-FMKD-FFT (MSE-CS | 0.9-0.1)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_mimic/MIMIC_All_Selected_Models/KD-MSEandCosineSimWeighted-alpha0p90/MIMIC_CXR-FMKD_full-finetuning_multirun-seed41' --kd_type_subdir_name 'KD-MSEandCosineSimWeighted-alpha0p90'
python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'mimic' --model_shortname 'CXR-FMKD-Direct-LP (MSE-CS | 0.9-0.1)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_mimic/MIMIC_All_Selected_Models/KD-MSEandCosineSimWeighted-alpha0p90/MIMIC_CXR-FMKD-1664to14_linear-probing_multirun-seed42' --kd_type_subdir_name 'KD-MSEandCosineSimWeighted-alpha0p90'
python '/Users/macuser/Desktop/Imperial/70078_MSc_AI_Individual_Project/code/cxr-fmkd/analysis/bias_analysis/evaluate_model_bias2.py' --config 'mimic' --model_shortname 'CXR-FMKD-Direct-FFT (MSE-CS | 0.9-0.1)' --model_dir '/Volumes/LaCie/IMPERIAL_MSc_AI_THESIS/outputs/outputs_mimic/MIMIC_All_Selected_Models/KD-MSEandCosineSimWeighted-alpha0p90/MIMIC_CXR-FMKD-1664to14_full-finetuning_multirun-seed45' --kd_type_subdir_name 'KD-MSEandCosineSimWeighted-alpha0p90'
